# GitHub Pages Configuration
remote_theme: jekyll/minima

# Site Metadata (Appears in the browser tab and footer)
title: AppFable Legal
description: Official legal documentation for the AppFable mobile application.
