# GitHub Pages Configuration
remote_theme: jekyll/minima

# Site Metadata (Appears in the browser tab and footer)
title: AppFabe Legal
description: Official legal documentation for the AppFabe mobile applications.
